In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import math
import statsmodels.api as sm
import statsmodels.formula.api as smf
import scipy.stats as stats
from math import log
import warnings
import warnings
warnings.filterwarnings('ignore')
import scipy.stats as st
!pip install linearmodels

In [2]:
#Importing Data File
data_file=pd.read_csv('DPFONAL_1.csv')

In [3]:
data_file

rev_Mean  mou_Mean  totmrc_Mean  da_Mean  ovrmou_Mean  ovrrev_Mean  \
0       76.9800      0.00      86.9800   0.0000         0.00       0.0000   
1       30.2700     28.25      30.0000   0.0000         0.00       0.0000   
2       46.1025    203.00      37.6575   0.0000        30.50      10.6750   
3       16.9900      3.25      16.9900   0.0000         0.00       0.0000   
4       40.0700    270.00      50.0700   0.0000         0.00       0.0000   
...         ...       ...          ...      ...          ...          ...   
89995       NaN       NaN          NaN      NaN          NaN          NaN   
89996   87.4175   2019.75      84.9900   0.7425        29.75       7.6475   
89997   86.2250    921.75      44.9900   0.0000       144.00      50.4000   
89998   32.3150    157.25      30.0000   1.2375         1.50       0.5850   
89999   94.9700    772.50      79.9900   0.7425         0.00       0.0000   

       vceovr_Mean  datovr_Mean  roam_Mean  rev_Range  ...  kid0_2  kid3_5  \
0           0.0000        0.000     0.0000       0.00  ...       U       U   
1           0.0000        0.000     0.0000       0.54  ...       U       U   
2          10.6750        0.000     0.0000      31.87  ...       U       U   
3           0.0000        0.000     0.0000       0.00  ...       U       U   
4           0.0000        0.000     0.0000       0.32  ...       U       U   
...            ...          ...        ...        ...  ...     ...     ...   
89995          NaN          NaN        NaN        NaN  ...       U       U   
89996       7.0625        0.585     4.0375      23.08  ...       U       U   
89997      50.4000        0.000     0.8350      33.91  ...       U       U   
89998       0.0000        0.585     0.4925       4.32  ...       U       U   
89999       0.0000        0.000     0.0000     129.89  ...       U       U   

       kid6_10  kid11_15  kid16_17  creditcd  car_buy  retdays  eqpdays  \
0            U         U         U         N  UNKNOWN      NaN      NaN   
1            U         U         Y         Y  UNKNOWN      NaN    566.0   
2            Y         Y         U         Y      New      NaN      7.0   
3            U         U         U         Y      New      NaN   1287.0   
4            U         U         U         Y      New      NaN   1131.0   
...        ...       ...       ...       ...      ...      ...      ...   
89995        U         U         U         N  UNKNOWN      NaN    326.0   
89996        U         U         U         N  UNKNOWN      NaN     83.0   
89997        U         U         Y         Y      New      NaN     88.0   
89998        Y         U         U         Y  UNKNOWN      NaN    106.0   
89999        U         U         U         Y  UNKNOWN     69.0     63.0   

       Customer_ID  
0          1077200  
1          1032004  
2          1003956  
3          1002348  
4          1003683  
...            ...  
89995      1008029  
89996      1072585  
89997      1086304  
89998      1006525  
89999      1015515  

[90000 rows x 173 columns]

In [4]:
data_file.columns

Index(['rev_Mean', 'mou_Mean', 'totmrc_Mean', 'da_Mean', 'ovrmou_Mean',
       'ovrrev_Mean', 'vceovr_Mean', 'datovr_Mean', 'roam_Mean', 'rev_Range',
       ...
       'kid0_2', 'kid3_5', 'kid6_10', 'kid11_15', 'kid16_17', 'creditcd',
       'car_buy', 'retdays', 'eqpdays', 'Customer_ID'],
      dtype='object', length=173)

In [5]:
#checking if there are any null values in the dataset
for col in data_file.columns:
    count=data_file[col].isna().sum()
    print(col,count)

rev_Mean 326
mou_Mean 326
totmrc_Mean 326
da_Mean 326
ovrmou_Mean 326
ovrrev_Mean 326
vceovr_Mean 326
datovr_Mean 326
roam_Mean 326
rev_Range 326
mou_Range 326
totmrc_Range 326
da_Range 326
ovrmou_Range 326
ovrrev_Range 326
vceovr_Range 326
datovr_Range 326
roam_Range 326
change_mou 814
change_rev 814
drop_vce_Mean 0
drop_dat_Mean 0
blck_vce_Mean 0
blck_dat_Mean 0
unan_vce_Mean 0
unan_dat_Mean 0
plcd_vce_Mean 0
plcd_dat_Mean 0
recv_vce_Mean 0
recv_sms_Mean 0
comp_vce_Mean 0
comp_dat_Mean 0
custcare_Mean 0
ccrndmou_Mean 0
cc_mou_Mean 0
inonemin_Mean 0
threeway_Mean 0
mou_cvce_Mean 0
mou_cdat_Mean 0
mou_rvce_Mean 0
owylis_vce_Mean 0
mouowylisv_Mean 0
iwylis_vce_Mean 0
mouiwylisv_Mean 0
peak_vce_Mean 0
peak_dat_Mean 0
mou_peav_Mean 0
mou_pead_Mean 0
opk_vce_Mean 0
opk_dat_Mean 0
mou_opkv_Mean 0
mou_opkd_Mean 0
drop_blk_Mean 0
attempt_Mean 0
complete_Mean 0
callfwdv_Mean 0
callwait_Mean 0
drop_vce_Range 0
drop_dat_Range 0
blck_vce_Range 0
blck_dat_Range 0
unan_vce_Range 0
unan_dat_Range 0


In [6]:
data_file.crclscod.unique()

array(['AA', 'BA', 'A', 'E', 'DA', 'C', 'D', 'B', 'CA', 'EA', 'ZA', 'J',
       'G', 'GA', 'M', 'A2', 'C2', 'Y', 'U', 'E4', 'Z', 'K', 'CC', 'I',
       'EM', 'O', 'V1', 'JF', 'B2', 'W', 'IF', 'Z2', 'ZY', 'CY', 'GY',
       'U1', 'C5', 'D5', 'E2', 'Z4', 'D4', 'Z1', 'EF', 'EC', 'Z5', 'H',
       'A3', 'S', 'L', 'V', 'P1', 'D2', 'TP', 'ZF'], dtype=object)

In [7]:
data_file['crclscod'].describe()

count     90000
unique       54
top          AA
freq      32864
Name: crclscod, dtype: object

In [8]:
data_file['churn'].describe()

count    90000.000000
mean         0.495211
std          0.499980
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000
Name: churn, dtype: float64

In [9]:
#I would like to threshold as 100 and combine all those are below 100 to one row.

In [10]:
after_threshold=data_file['crclscod']=data_file['crclscod'].replace({'K':'B2','W':'B2','C5':'B2','V1':'B2','U1':'B2','Z5':'B2','EM':'B2','Y':'B2','EC':'B2','GY':'B2','CC':'B2','O':'B2','E2':'B2','IF':'B2','Z1':'B2','H':'B2','L':'B2','Z2':'B2','D2':'B2','TP':'B2','P1':'B2','A3':'B2','EF':'B2','S':'B2','V':'B2','ZF':'B2'})

In [11]:
after_threshold

0        AA
1        BA
2         A
3         A
4         A
         ..
89995     C
89996    CA
89997    ZA
89998    CA
89999     U
Name: crclscod, Length: 90000, dtype: object

In [12]:
dfs=data_file.replace({'K':'B2','W':'B2','C5':'B2','V1':'B2','U1':'B2','Z5':'B2','EM':'B2','Y':'B2','EC':'B2','GY':'B2','CC':'B2','O':'B2','E2':'B2','IF':'B2','Z1':'B2','H':'B2','L':'B2','Z2':'B2','D2':'B2','TP':'B2','P1':'B2','A3':'B2','EF':'B2','S':'B2','V':'B2','ZF':'B2'}).groupby(['crclscod'])['churn'].sum()

In [13]:
pd.DataFrame(dfs)

churn
crclscod       
A          7894
A2          479
AA        16634
B          1939
B2          371
BA         5945
C           633
C2           75
CA         3515
CY           77
D           100
D4          102
D5           20
DA         1479
E           121
E4          233
EA         2337
G           114
GA          129
I           109
J            80
JF          100
M            81
U           201
Z            84
Z4           93
ZA         1572
ZY           52

In [14]:
# sorting w.r.t saleprice column
dfss=dfs.sort_values(ascending=True)

In [15]:
dfss

crclscod
D5       20
ZY       52
C2       75
CY       77
J        80
M        81
Z        84
Z4       93
D       100
JF      100
D4      102
I       109
G       114
E       121
GA      129
U       201
E4      233
B2      371
A2      479
C       633
DA     1479
ZA     1572
B      1939
EA     2337
CA     3515
BA     5945
A      7894
AA    16634
Name: churn, dtype: int64

In [16]:
after_threshold=(data_file['crclscod'].value_counts())

In [17]:
dfsss=after_threshold.sort_values(ascending=True)

In [18]:
dfsss

D5      104
ZY      105
M       160
C2      164
CY      169
J       172
Z       174
JF      176
G       214
I       221
Z4      223
D       227
GA      255
D4      273
E       302
U       428
E4      767
A2      784
B2      835
C      1324
ZA     3158
DA     3328
B      3690
EA     5720
CA     7529
BA    11408
A     15226
AA    32864
Name: crclscod, dtype: int64

In [19]:
concat=pd.concat([dfsss.reset_index(drop=False),dfss.reset_index(drop=True)],axis=1)

In [20]:
concat_latest=pd.concat([dfsss.reset_index(drop=False),dfss.reset_index(drop=True)],axis=1)

In [21]:
concat

index  crclscod  churn
0     D5       104     20
1     ZY       105     52
2      M       160     75
3     C2       164     77
4     CY       169     80
5      J       172     81
6      Z       174     84
7     JF       176     93
8      G       214    100
9      I       221    100
10    Z4       223    102
11     D       227    109
12    GA       255    114
13    D4       273    121
14     E       302    129
15     U       428    201
16    E4       767    233
17    A2       784    371
18    B2       835    479
19     C      1324    633
20    ZA      3158   1479
21    DA      3328   1572
22     B      3690   1939
23    EA      5720   2337
24    CA      7529   3515
25    BA     11408   5945
26     A     15226   7894
27    AA     32864  16634

In [22]:
#concat['churn_no']=concat['churn']-concat['crclscod']
concat['churn_rate']=concat['churn']/concat['crclscod']
concat['churn_no']=concat['crclscod']-concat['churn']
concat['standard_deviation']=((concat['churn_rate']*(1-concat['churn_rate'])**2+concat['churn_no']*(0-concat['churn_rate'])**2)/concat['churn'])**0.5
concat

index  crclscod  churn  churn_rate  churn_no  standard_deviation
0     D5       104     20    0.192308        84            0.401993
1     ZY       105     52    0.495238        53            0.502398
2      M       160     75    0.468750        85            0.500787
3     C2       164     77    0.469512        87            0.500786
4     CY       169     80    0.473373        89            0.500931
5      J       172     81    0.470930        91            0.500782
6      Z       174     84    0.482759        90            0.501239
7     JF       176     93    0.528409        83            0.500456
8      G       214    100    0.467290       114            0.500256
9      I       221    100    0.452489       121            0.499098
10    Z4       223    102    0.457399       121            0.499505
11     D       227    109    0.480176       118            0.500797
12    GA       255    114    0.447059       141            0.498394
13    D4       273    121    0.443223       152            0.497908
14     E       302    129    0.427152       173            0.495762
15     U       428    201    0.469626       227            0.499735
16    E4       767    233    0.303781       534            0.460576
17    A2       784    371    0.473214       413            0.499636
18    B2       835    479    0.573653       356            0.494766
19     C      1324    633    0.478097       691            0.499726
20    ZA      3158   1479    0.468334      1679            0.499086
21    DA      3328   1572    0.472356      1756            0.499319
22     B      3690   1939    0.525474      1751            0.499412
23    EA      5720   2337    0.408566      3383            0.491631
24    CA      7529   3515    0.466861      4014            0.498938
25    BA     11408   5945    0.521126      5463            0.499574
26     A     15226   7894    0.518455      7332            0.499675
27    AA     32864  16634    0.506147     16230            0.499970

#### Margin of Error , Upper bound lower bounds with confidence interval 95% and width differencce with 95% confidence interval

In [23]:
p_fm = concat['churn']/(concat['crclscod'])

In [24]:
p_fm

0     0.192308
1     0.495238
2     0.468750
3     0.469512
4     0.473373
5     0.470930
6     0.482759
7     0.528409
8     0.467290
9     0.452489
10    0.457399
11    0.480176
12    0.447059
13    0.443223
14    0.427152
15    0.469626
16    0.303781
17    0.473214
18    0.573653
19    0.478097
20    0.468334
21    0.472356
22    0.525474
23    0.408566
24    0.466861
25    0.521126
26    0.518455
27    0.506147
dtype: float64

In [25]:
n=concat['crclscod']

In [26]:
# Calculate the standard error

se = np.sqrt(p_fm * (1 - p_fm) / n)

In [27]:
se

0     0.038646
1     0.048793
2     0.039451
3     0.038971
4     0.038407
5     0.038060
6     0.037882
7     0.037628
8     0.034106
9     0.033481
10    0.033361
11    0.033160
12    0.031135
13    0.030066
14    0.028465
15    0.024124
16    0.016606
17    0.017832
18    0.017114
19    0.013728
20    0.008880
21    0.008654
22    0.008220
23    0.006500
24    0.005750
25    0.004677
26    0.004049
27    0.002758
dtype: float64

In [28]:
#Now construct the CI using the formulas above. The z-score is 1.96 for a 95% confidence interval.
z_score =1.96
lcb = p_fm - z_score* se #lower bound 
ucb = p_fm + z_score* se #upper bound 

In [29]:
lcb

0     0.116562
1     0.399604
2     0.391426
3     0.393129
4     0.398095
5     0.396332
6     0.408509
7     0.454658
8     0.400442
9     0.386865
10    0.392012
11    0.415182
12    0.386034
13    0.384295
14    0.371361
15    0.422344
16    0.271234
17    0.438265
18    0.540108
19    0.451190
20    0.450930
21    0.455394
22    0.509362
23    0.395827
24    0.455592
25    0.511958
26    0.510519
27    0.500741
dtype: float64

In [30]:
ucb

0     0.268054
1     0.590872
2     0.546074
3     0.545895
4     0.548650
5     0.545528
6     0.557008
7     0.602160
8     0.534138
9     0.518112
10    0.522786
11    0.545170
12    0.508084
13    0.502152
14    0.482943
15    0.516909
16    0.336328
17    0.508164
18    0.607197
19    0.505004
20    0.485738
21    0.489317
22    0.541586
23    0.421306
24    0.478131
25    0.530293
26    0.526392
27    0.511552
dtype: float64

In [31]:
#concat['churn_no']=concat['churn']-concat['crclscod']
concat['churn_no']=concat['crclscod']-concat['churn']
concat['churn_rate']=concat['churn']/concat['crclscod']
concat['lower_bound']=lcb
concat['upper_bound']=ucb
concat['width 95% confidence Interval ']=concat['upper_bound']-concat['lower_bound']
concat['margin of error']=se

concat['standard_deviation']=((concat['churn_rate']*(1-concat['churn_rate'])**2+concat['churn_no']*(0-concat['churn_rate'])**2)/concat['churn'])**0.5
concat
concat

index  crclscod  churn  churn_rate  churn_no  standard_deviation  \
0     D5       104     20    0.192308        84            0.401993   
1     ZY       105     52    0.495238        53            0.502398   
2      M       160     75    0.468750        85            0.500787   
3     C2       164     77    0.469512        87            0.500786   
4     CY       169     80    0.473373        89            0.500931   
5      J       172     81    0.470930        91            0.500782   
6      Z       174     84    0.482759        90            0.501239   
7     JF       176     93    0.528409        83            0.500456   
8      G       214    100    0.467290       114            0.500256   
9      I       221    100    0.452489       121            0.499098   
10    Z4       223    102    0.457399       121            0.499505   
11     D       227    109    0.480176       118            0.500797   
12    GA       255    114    0.447059       141            0.498394   
13    D4       273    121    0.443223       152            0.497908   
14     E       302    129    0.427152       173            0.495762   
15     U       428    201    0.469626       227            0.499735   
16    E4       767    233    0.303781       534            0.460576   
17    A2       784    371    0.473214       413            0.499636   
18    B2       835    479    0.573653       356            0.494766   
19     C      1324    633    0.478097       691            0.499726   
20    ZA      3158   1479    0.468334      1679            0.499086   
21    DA      3328   1572    0.472356      1756            0.499319   
22     B      3690   1939    0.525474      1751            0.499412   
23    EA      5720   2337    0.408566      3383            0.491631   
24    CA      7529   3515    0.466861      4014            0.498938   
25    BA     11408   5945    0.521126      5463            0.499574   
26     A     15226   7894    0.518455      7332            0.499675   
27    AA     32864  16634    0.506147     16230            0.499970   

    lower_bound  upper_bound  width 95% confidence Interval   margin of error  
0      0.116562     0.268054                        0.151492         0.038646  
1      0.399604     0.590872                        0.191268         0.048793  
2      0.391426     0.546074                        0.154649         0.039451  
3      0.393129     0.545895                        0.152765         0.038971  
4      0.398095     0.548650                        0.150555         0.038407  
5      0.396332     0.545528                        0.149196         0.038060  
6      0.408509     0.557008                        0.148499         0.037882  
7      0.454658     0.602160                        0.147502         0.037628  
8      0.400442     0.534138                        0.133696         0.034106  
9      0.386865     0.518112                        0.131247         0.033481  
10     0.392012     0.522786                        0.130774         0.033361  
11     0.415182     0.545170                        0.129987         0.033160  
12     0.386034     0.508084                        0.122050         0.031135  
13     0.384295     0.502152                        0.117857         0.030066  
14     0.371361     0.482943                        0.111582         0.028465  
15     0.422344     0.516909                        0.094565         0.024124  
16     0.271234     0.336328                        0.065094         0.016606  
17     0.438265     0.508164                        0.069899         0.017832  
18     0.540108     0.607197                        0.067089         0.017114  
19     0.451190     0.505004                        0.053814         0.013728  
20     0.450930     0.485738                        0.034808         0.008880  
21     0.455394     0.489317                        0.033923         0.008654  
22     0.509362     0.541586                        0.032224         0.008220  
23     0.395827     0.4

In [32]:
New_Table=concat_latest
New_Table['churn_no']=New_Table['crclscod']-New_Table['churn']
New_Table['churn_rate']=New_Table['churn']/New_Table['crclscod']
#calculate logit
p=New_Table['churn_rate']/(1-New_Table['churn_rate'])
New_Table['p']=p
New_Table['logit of churn_rate']=[log(x) for x in New_Table['p']]


New_Table

index  crclscod  churn  churn_no  churn_rate         p  logit of churn_rate
0     D5       104     20        84    0.192308  0.238095            -1.435085
1     ZY       105     52        53    0.495238  0.981132            -0.019048
2      M       160     75        85    0.468750  0.882353            -0.125163
3     C2       164     77        87    0.469512  0.885057            -0.122103
4     CY       169     80        89    0.473373  0.898876            -0.106610
5      J       172     81        91    0.470930  0.890110            -0.116410
6      Z       174     84        90    0.482759  0.933333            -0.068993
7     JF       176     93        83    0.528409  1.120482             0.113759
8      G       214    100       114    0.467290  0.877193            -0.131028
9      I       221    100       121    0.452489  0.826446            -0.190620
10    Z4       223    102       121    0.457399  0.842975            -0.170818
11     D       227    109       118    0.480176  0.923729            -0.079337
12    GA       255    114       141    0.447059  0.808511            -0.212561
13    D4       273    121       152    0.443223  0.796053            -0.228090
14     E       302    129       173    0.427152  0.745665            -0.293479
15     U       428    201       227    0.469626  0.885463            -0.121645
16    E4       767    233       534    0.303781  0.436330            -0.829357
17    A2       784    371       413    0.473214  0.898305            -0.107246
18    B2       835    479       356    0.573653  1.345506             0.296770
19     C      1324    633       691    0.478097  0.916064            -0.087669
20    ZA      3158   1479      1679    0.468334  0.880881            -0.126832
21    DA      3328   1572      1756    0.472356  0.895216            -0.110690
22     B      3690   1939      1751    0.525474  1.107367             0.101985
23    EA      5720   2337      3383    0.408566  0.690807            -0.369895
24    CA      7529   3515      4014    0.466861  0.875685            -0.132749
25    BA     11408   5945      5463    0.521126  1.088230             0.084552
26     A     15226   7894      7332    0.518455  1.076650             0.073855
27    AA     32864  16634     16230    0.506147  1.024892             0.024587

(e) Based on the table produced in part (d), identify all cells with “similar” logit.  
What is your definition that logits are similar to each other?

Answer: According to my understanding i would combine all of those logits that are having similar value. Since we cannot do that as we are having almost unique values to every defined cell on the top. I will set a threshold and combine all of them.

In [33]:
New_Table=concat_latest
New_Table['churn_no']=New_Table['crclscod']-New_Table['churn']
New_Table['churn_rate']=New_Table['churn']/New_Table['crclscod']
#calculate logit
p=New_Table['churn_rate']/(1-New_Table['churn_rate'])
New_Table['p']=p
New_Table['logit of churn_rate']=[log(x) for x in New_Table['p']]
New_Table['Shift']=New_Table['logit of churn_rate'].shift(1)
New_Table['Shift']= New_Table['Shift'].fillna(0)

New_Table['Difference'] = New_Table.apply(lambda x: x['logit of churn_rate'] - x['Shift'], axis=1)


New_Table

index  crclscod  churn  churn_no  churn_rate         p  \
0     D5       104     20        84    0.192308  0.238095   
1     ZY       105     52        53    0.495238  0.981132   
2      M       160     75        85    0.468750  0.882353   
3     C2       164     77        87    0.469512  0.885057   
4     CY       169     80        89    0.473373  0.898876   
5      J       172     81        91    0.470930  0.890110   
6      Z       174     84        90    0.482759  0.933333   
7     JF       176     93        83    0.528409  1.120482   
8      G       214    100       114    0.467290  0.877193   
9      I       221    100       121    0.452489  0.826446   
10    Z4       223    102       121    0.457399  0.842975   
11     D       227    109       118    0.480176  0.923729   
12    GA       255    114       141    0.447059  0.808511   
13    D4       273    121       152    0.443223  0.796053   
14     E       302    129       173    0.427152  0.745665   
15     U       428    201       227    0.469626  0.885463   
16    E4       767    233       534    0.303781  0.436330   
17    A2       784    371       413    0.473214  0.898305   
18    B2       835    479       356    0.573653  1.345506   
19     C      1324    633       691    0.478097  0.916064   
20    ZA      3158   1479      1679    0.468334  0.880881   
21    DA      3328   1572      1756    0.472356  0.895216   
22     B      3690   1939      1751    0.525474  1.107367   
23    EA      5720   2337      3383    0.408566  0.690807   
24    CA      7529   3515      4014    0.466861  0.875685   
25    BA     11408   5945      5463    0.521126  1.088230   
26     A     15226   7894      7332    0.518455  1.076650   
27    AA     32864  16634     16230    0.506147  1.024892   

    logit of churn_rate     Shift  Difference  
0             -1.435085  0.000000   -1.435085  
1             -0.019048 -1.435085    1.416036  
2             -0.125163 -0.019048   -0.106115  
3             -0.122103 -0.125163    0.003060  
4             -0.106610 -0.122103    0.015493  
5             -0.116410 -0.106610   -0.009801  
6             -0.068993 -0.116410    0.047417  
7              0.113759 -0.068993    0.182752  
8             -0.131028  0.113759   -0.244787  
9             -0.190620 -0.131028   -0.059592  
10            -0.170818 -0.190620    0.019803  
11            -0.079337 -0.170818    0.091481  
12            -0.212561 -0.079337   -0.133225  
13            -0.228090 -0.212561   -0.015529  
14            -0.293479 -0.228090   -0.065389  
15            -0.121645 -0.293479    0.171834  
16            -0.829357 -0.121645   -0.707712  
17            -0.107246 -0.829357    0.722112  
18             0.296770 -0.107246    0.404015  
19            -0.087669  0.296770   -0.384439  
20            -0.126832 -0.087669   -0.039163  
21            -0.110690 -0.126832    0.016142  
22             0.101985 -0.110690    0.212675  
23            -0.369895  0.101985   -0.471880  
24            -0.132749 -0.369895    0.237146  
25             0.084552 -0.132749    0.217301  
26             0.073855  0.084552   -0.010698  
27             0.024587  0.073855   -0.049267

## Sorting by Churn Rate

In [34]:
sort=pd.concat([dfsss.reset_index(drop=False),dfss.reset_index(drop=True)],axis=1)

In [35]:
sort

index  crclscod  churn
0     D5       104     20
1     ZY       105     52
2      M       160     75
3     C2       164     77
4     CY       169     80
5      J       172     81
6      Z       174     84
7     JF       176     93
8      G       214    100
9      I       221    100
10    Z4       223    102
11     D       227    109
12    GA       255    114
13    D4       273    121
14     E       302    129
15     U       428    201
16    E4       767    233
17    A2       784    371
18    B2       835    479
19     C      1324    633
20    ZA      3158   1479
21    DA      3328   1572
22     B      3690   1939
23    EA      5720   2337
24    CA      7529   3515
25    BA     11408   5945
26     A     15226   7894
27    AA     32864  16634

In [36]:
sort['churn_rate']=sort['churn']/sort['crclscod']



In [37]:
#sorting values based on churn rate
sortd=sort.sort_values("churn_rate")

In [38]:

sortd['churn_rate']=sortd['churn']/sortd['crclscod']
#calculate logit
p=sortd['churn_rate']/(1-sortd['churn_rate'])

sortd['logit of churn_rate']=[log(x) for x in p]
sortd['Shift']=sortd['logit of churn_rate'].shift(1)
sortd['Shift']= sortd['Shift'].fillna(0)

sortd['Difference'] = sortd.apply(lambda x: x['logit of churn_rate'] - x['Shift'], axis=1)
sortd.at[0,'Difference']=0


sortd

index  crclscod  churn  churn_rate  logit of churn_rate     Shift  \
0     D5       104     20    0.192308            -1.435085  0.000000   
16    E4       767    233    0.303781            -0.829357 -1.435085   
23    EA      5720   2337    0.408566            -0.369895 -0.829357   
14     E       302    129    0.427152            -0.293479 -0.369895   
13    D4       273    121    0.443223            -0.228090 -0.293479   
12    GA       255    114    0.447059            -0.212561 -0.228090   
9      I       221    100    0.452489            -0.190620 -0.212561   
10    Z4       223    102    0.457399            -0.170818 -0.190620   
24    CA      7529   3515    0.466861            -0.132749 -0.170818   
8      G       214    100    0.467290            -0.131028 -0.132749   
20    ZA      3158   1479    0.468334            -0.126832 -0.131028   
2      M       160     75    0.468750            -0.125163 -0.126832   
3     C2       164     77    0.469512            -0.122103 -0.125163   
15     U       428    201    0.469626            -0.121645 -0.122103   
5      J       172     81    0.470930            -0.116410 -0.121645   
21    DA      3328   1572    0.472356            -0.110690 -0.116410   
17    A2       784    371    0.473214            -0.107246 -0.110690   
4     CY       169     80    0.473373            -0.106610 -0.107246   
19     C      1324    633    0.478097            -0.087669 -0.106610   
11     D       227    109    0.480176            -0.079337 -0.087669   
6      Z       174     84    0.482759            -0.068993 -0.079337   
1     ZY       105     52    0.495238            -0.019048 -0.068993   
27    AA     32864  16634    0.506147             0.024587 -0.019048   
26     A     15226   7894    0.518455             0.073855  0.024587   
25    BA     11408   5945    0.521126             0.084552  0.073855   
22     B      3690   1939    0.525474             0.101985  0.084552   
7     JF       176     93    0.528409             0.113759  0.101985   
18    B2       835    479    0.573653             0.296770  0.113759   

    Difference  
0     0.000000  
16    0.605727  
23    0.459463  
14    0.076416  
13    0.065389  
12    0.015529  
9     0.021941  
10    0.019803  
24    0.038069  
8     0.001720  
20    0.004196  
2     0.001669  
3     0.003060  
15    0.000458  
5     0.005235  
21    0.005721  
17    0.003444  
4     0.000636  
19    0.018940  
11    0.008333  
6     0.010344  
1     0.049945  
27    0.043636  
26    0.049267  
25    0.010698  
22    0.017433  
7     0.011774  
18    0.183011

(f) Obtain New Categories based on your answer in part (e)

In [39]:
logit_threshold=sortd[sortd["Difference"]<0.011774]

In [40]:
logit_threshold

index  crclscod  churn  churn_rate  logit of churn_rate     Shift  \
0     D5       104     20    0.192308            -1.435085  0.000000   
8      G       214    100    0.467290            -0.131028 -0.132749   
20    ZA      3158   1479    0.468334            -0.126832 -0.131028   
2      M       160     75    0.468750            -0.125163 -0.126832   
3     C2       164     77    0.469512            -0.122103 -0.125163   
15     U       428    201    0.469626            -0.121645 -0.122103   
5      J       172     81    0.470930            -0.116410 -0.121645   
21    DA      3328   1572    0.472356            -0.110690 -0.116410   
17    A2       784    371    0.473214            -0.107246 -0.110690   
4     CY       169     80    0.473373            -0.106610 -0.107246   
11     D       227    109    0.480176            -0.079337 -0.087669   
6      Z       174     84    0.482759            -0.068993 -0.079337   
25    BA     11408   5945    0.521126             0.084552  0.073855   
7     JF       176     93    0.528409             0.113759  0.101985   

    Difference  
0     0.000000  
8     0.001720  
20    0.004196  
2     0.001669  
3     0.003060  
15    0.000458  
5     0.005235  
21    0.005721  
17    0.003444  
4     0.000636  
11    0.008333  
6     0.010344  
25    0.010698  
7     0.011774

In [41]:
#sorting with index
so=sortd.reset_index(drop=True)

In [42]:
so

index  crclscod  churn  churn_rate  logit of churn_rate     Shift  \
0     D5       104     20    0.192308            -1.435085  0.000000   
1     E4       767    233    0.303781            -0.829357 -1.435085   
2     EA      5720   2337    0.408566            -0.369895 -0.829357   
3      E       302    129    0.427152            -0.293479 -0.369895   
4     D4       273    121    0.443223            -0.228090 -0.293479   
5     GA       255    114    0.447059            -0.212561 -0.228090   
6      I       221    100    0.452489            -0.190620 -0.212561   
7     Z4       223    102    0.457399            -0.170818 -0.190620   
8     CA      7529   3515    0.466861            -0.132749 -0.170818   
9      G       214    100    0.467290            -0.131028 -0.132749   
10    ZA      3158   1479    0.468334            -0.126832 -0.131028   
11     M       160     75    0.468750            -0.125163 -0.126832   
12    C2       164     77    0.469512            -0.122103 -0.125163   
13     U       428    201    0.469626            -0.121645 -0.122103   
14     J       172     81    0.470930            -0.116410 -0.121645   
15    DA      3328   1572    0.472356            -0.110690 -0.116410   
16    A2       784    371    0.473214            -0.107246 -0.110690   
17    CY       169     80    0.473373            -0.106610 -0.107246   
18     C      1324    633    0.478097            -0.087669 -0.106610   
19     D       227    109    0.480176            -0.079337 -0.087669   
20     Z       174     84    0.482759            -0.068993 -0.079337   
21    ZY       105     52    0.495238            -0.019048 -0.068993   
22    AA     32864  16634    0.506147             0.024587 -0.019048   
23     A     15226   7894    0.518455             0.073855  0.024587   
24    BA     11408   5945    0.521126             0.084552  0.073855   
25     B      3690   1939    0.525474             0.101985  0.084552   
26    JF       176     93    0.528409             0.113759  0.101985   
27    B2       835    479    0.573653             0.296770  0.113759   

    Difference  
0     0.000000  
1     0.605727  
2     0.459463  
3     0.076416  
4     0.065389  
5     0.015529  
6     0.021941  
7     0.019803  
8     0.038069  
9     0.001720  
10    0.004196  
11    0.001669  
12    0.003060  
13    0.000458  
14    0.005235  
15    0.005721  
16    0.003444  
17    0.000636  
18    0.018940  
19    0.008333  
20    0.010344  
21    0.049945  
22    0.043636  
23    0.049267  
24    0.010698  
25    0.017433  
26    0.011774  
27    0.183011

In [43]:
logit_1=so.loc[3:4].sum()

In [44]:
logit_1

index                       ED4
crclscod                    575
churn                       250
churn_rate             0.870376
logit of churn_rate   -0.521569
Shift                 -0.663374
Difference             0.141805
dtype: object

In [45]:
l2=so.loc[5:8].sum()
l2


index                   GAIZ4CA
crclscod                   8228
churn                      3831
churn_rate             1.823808
logit of churn_rate   -0.706748
Shift                  -0.80209
Difference             0.095341
dtype: object

In [46]:
l3=so.loc[9:17].sum()
l3

index                  GZAMC2UJDAA2CY
crclscod                         8577
churn                            4036
churn_rate                   4.233386
logit of churn_rate         -1.067727
Shift                       -1.093866
Difference                   0.026139
dtype: object

In [47]:
l4=so.loc[21:26].sum()
l4

index                  ZYAAABABJF
crclscod                    63469
churn                       32557
churn_rate               3.094849
logit of churn_rate      0.379691
Shift                    0.196939
Difference               0.182752
dtype: object

In [48]:
l6=so.loc[24:27].sum()
l6

index                   BABJFB2
crclscod                  16109
churn                      8456
churn_rate             2.148662
logit of churn_rate    0.597067
Shift                  0.374151
Difference             0.222915
dtype: object

In [49]:
Final_result=so[['index','churn']]

In [50]:
Final_result

index  churn
0     D5     20
1     E4    233
2     EA   2337
3      E    129
4     D4    121
5     GA    114
6      I    100
7     Z4    102
8     CA   3515
9      G    100
10    ZA   1479
11     M     75
12    C2     77
13     U    201
14     J     81
15    DA   1572
16    A2    371
17    CY     80
18     C    633
19     D    109
20     Z     84
21    ZY     52
22    AA  16634
23     A   7894
24    BA   5945
25     B   1939
26    JF     93
27    B2    479

Clusters formed 

In [51]:
final=Final_result.replace({'E':'D4','I':'GA','Z4':'ZA','CA':'ZA','ZA':'G','M':'G','C2':'G','U':'G','J':'G','DA':'G','A2':'G','CY':'G','AA':'ZY','A':'ZY','B':'BA','JF':'BA'}).groupby(['index'])['churn'].sum().reset_index(name='churn')

In [52]:
final=pd.DataFrame(final)

In [53]:
final

index  churn
0     B2    479
1     BA   7977
2      C    633
3      D    109
4     D4    250
5     D5     20
6     E4    233
7     EA   2337
8      G   4036
9     GA    214
10     Z     84
11    ZA   3617
12    ZY  24580

### Sum (Deviation) Coding



In [54]:
from patsy.contrasts import Sum
from statsmodels.formula.api import ols

In [55]:
deviation = Sum().code_without_intercept(final['index'])

In [56]:
print(deviation.matrix)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]


In [57]:
#ols for the datafile
mod = ols("churn ~ C(crclscod, Diff)", data=data_file)
res = mod.fit()
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                  churn   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                  0.006
Method:                 Least Squares   F-statistic:                     21.25
Date:                Mon, 26 Sep 2022   Prob (F-statistic):          2.01e-103
Time:                        22:09:26   Log-Likelihood:                -65031.
No. Observations:               90000   AIC:                         1.301e+05
Df Residuals:                   89972   BIC:                         1.304e+05
Df Model:                          27                                         
Covariance Type:            nonrobust                                         
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                 